namespace d20 {
    public enum Proficiency {
        // Armor
        LIGHT_ARMOR, MEDIUM_ARMOR, HEAVY_ARMOR,
        // Shields
        SHIELDS,
        // Simple melee weapons
        SIMPLE_MELEE_WEAPONS,
        CLUB, DAGGER, GREATCLUB, HANDAXE, JAVELIN, LIGHT_HAMMER, MACE, QUARTERSTAFF, SICKLE, SPEAR,
        // Simple ranged weapons
        SIMPLE_RANGED_WEAPONS,
        CROSSBOW_LIGHT, DARK, SHORTBOW, SLING,
        // Martial melee weapons
        MARTIAL_MELEE_WEAPONS,
        BATTLEAXE, FLAIL, GLAIVE, GREATAXE, GREATSWORD, HALBERD, LANCE, LONGSWORD, MAUL, 
        MORNINGSTAR, PIKE, RAPIER, SCIMITAR, SHORTSWORD, TRIDENT, WAR_PICK, WARHAMMER, WHIP,
        // Martial ranged weapons
        MARTIAL_RANGED_WEAPONS,
        BLOWGUN, CROSSBOW_HAND, CROSSBOW_HEAVY, LONGBOW, NET,
        // Artisan Tools
        ALCHEMIST, BREWER, CALLIGRAPHER, CARPENTER, CARTOGRAPHER, COBBLER, COOK, GLASSBLOWER, 
        JEWELER, LEATHERWORKER, MASON, PAINTER, POTTER, SMITH, TINKER, WEAVER, WOODCARVER, 
        DISGUISE_KIT, FORGER_KIT,
        // Gaming Set
        DICE_SET, PLAYING_CARD_SET,
        // Musical instruments
        BAGPIPES, DRUM, DULCIMER, FLUTE, LUTE, LYRE, HORN, PAN_FLUTE, SHAWN, VIOL,
        // Others
        HERBALISM_KIT, NAVIGATOR_TOOLS, POISONER_KIT, THIEVES_TOOLS,
        // Mounts
        CAMEL, DONKEY, ELEPHANT, HORSE_DRAFT, HORSE_RIDING, MASTIFF, PONY, WARHORSE, 
    }
}